// angular/adminpro/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/interfaces/user';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  providers: [AuthService],
})
export class RegisterComponent implements OnInit {
  name: string = '';
  email: string = '';
  password: string = '';
  confirmedPassword: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {}

  onSubmit() {
    const errMsgs = [];

    if (this.name.trim() === '') errMsgs.push('Name is required');

    if (this.name.trim() === '') errMsgs.push('Email is required');

    if (this.name.trim() === '') errMsgs.push('Password is required');

    if (this.name.trim() === '') errMsgs.push('Confirm Password is required');

    if (errMsgs.length > 0) return alert(errMsgs.join('\n'));

    if (this.password !== this.confirmedPassword)
      return alert('Password does not match');

    const newUser: User = {
      name: this.name,
      email: this.email,
      password: this.password,
    };

    this.authService.register(newUser).subscribe((res) => {
      if (res.status == 200) {
        if (res.body.ok) {
          this.router.navigate(['/login']);
        } else {
          alert('Email already has an account');
        }
      } else {
        alert(res.body);
      }
    });
  }
}

<section
  id="wrapper"
  class="login-register login-sidebar"
  style="background-image: url(../assets/images/background/login-register.jpg)"
>
  <div class="login-box card">
    <div class="card-body">
      <form
        class="form-horizontal form-material"
        id="loginform"
        (ngSubmit)="onSubmit()"
      >
        <a href="javascript:void(0)" class="text-center db"
          ><img src="./assets/images/logo-icon.png" alt="Home" /><br /><img
            src="./assets/images/logo-text.png"
            alt="Home"
        /></a>
        <h3 class="box-title m-t-40 m-b-0">Register Now</h3>
        <small>Create your account and enjoy</small>
        <div class="form-group m-t-20">
          <div class="col-xs-12">
            <input
              class="form-control"
              type="text"
              required=""
              placeholder="Name"
              name="name"
              [(ngModel)]="name"
            />
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <input
              class="form-control"
              type="text"
              required=""
              placeholder="Email"
              name="email"
              [(ngModel)]="email"
            />
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <input
              class="form-control"
              type="password"
              required=""
              placeholder="Password"
              name="password"
              [(ngModel)]="password"
            />
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <input
              class="form-control"
              type="password"
              required
              placeholder="Confirm Password"
              name="confirmedPassword"
              [(ngModel)]="confirmedPassword"
            />
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-12">
            <div class="checkbox checkbox-primary p-t-0">
              <input id="checkbox-signup" type="checkbox" />
              <label for="checkbox-signup">
                I agree to all <a href="#">Terms</a></label
              >
            </div>
          </div>
        </div>
        <div class="form-group text-center m-t-20">
          <div class="col-xs-12">
            <button
              class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light"
              type="submit"
            >
              Sign Up
            </button>
          </div>
        </div>
        <div class="form-group m-b-0">
          <div class="col-sm-12 text-center">
            <p>
              Already have an account?
              <a
                routerLink="/login"
                routerLinkActive="router-link-active"
                class="text-info m-l-5"
                ><b>Sign In</b></a
              >
            </p>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

// vue/dashboard-vue/src/components/auth/Register.vue
<template>
  <!-- ============================================================== -->
  <!-- Main wrapper - style you can find in pages.scss -->
  <!-- ============================================================== -->
  <section
    id="wrapper"
    class="login-register login-sidebar"
    style="background-image: url(/assets/images/background/login-register.jpg)"
  >
    <div class="login-box card">
      <div class="card-body">
        <form
          class="form-horizontal form-material"
          id="loginform"
          action="index.html"
        >
          <a href="javascript:void(0)" class="text-center db"
            ><img src="/assets/images/logo-icon.png" alt="Home" /><br /><img
              src="/assets/images/logo-text.png"
              alt="Home"
          /></a>
          <h3 class="box-title m-t-40 m-b-0">Register Now</h3>
          <small>Create your account and enjoy</small>
          <div class="form-group m-t-20">
            <div class="col-xs-12">
              <input
                class="form-control"
                type="text"
                required=""
                placeholder="Name"
              />
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <input
                class="form-control"
                type="text"
                required=""
                placeholder="Email"
              />
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <input
                class="form-control"
                type="password"
                required=""
                placeholder="Password"
              />
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <input
                class="form-control"
                type="password"
                required=""
                placeholder="Confirm Password"
              />
            </div>
          </div>
          <div class="form-group row">
            <div class="col-md-12">
              <div class="checkbox checkbox-primary p-t-0">
                <input id="checkbox-signup" type="checkbox" />
                <label for="checkbox-signup">
                  I agree to all <a href="#">Terms</a></label
                >
              </div>
            </div>
          </div>
          <div class="form-group text-center m-t-20">
            <div class="col-xs-12">
              <button
                class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light"
                type="submit"
              >
                Sign Up
              </button>
            </div>
          </div>
          <div class="form-group m-b-0">
            <div class="col-sm-12 text-center">
              <p>
                Already have an account?
                <a href="pages-login-2.html" class="text-info m-l-5"
                  ><b>Sign In</b></a
                >
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
  <!-- ============================================================== -->
  <!-- End Wrapper -->
  <!-- ============================================================== -->
</template>

<script>
export default {
  name: "RegisterComponent",
};
</script>

<style>
/*
Template Name: Admin pro Admin
Author: Wrappixel
Email: niravjoshi87@gmail.com
File: scss
*/
/*
Template Name: Admin Pro Admin
Author: Wrappixel
Email: niravjoshi87@gmail.com
File: scss
*/
/*Theme Colors*/
/*bootstrap Color*/
/*Light colors*/
/*Normal Color*/
/*Extra Variable*/
/*******************
Login register and recover password Page
******************/
.login-register {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  height: 100%;
  width: 100%;
  padding: 10% 0;
  position: fixed;
}

.login-box {
  width: 400px;
  margin: 0 auto;
}
.login-box .footer {
  width: 100%;
  left: 0px;
  right: 0px;
}
.login-box .social {
  display: block;
  margin-bottom: 30px;
}

#recoverform {
  display: none;
}

.login-sidebar {
  padding: 0px;
  margin-top: 0px;
}
.login-sidebar .login-box {
  right: 0px;
  position: absolute;
  height: 100%;
}
</style>
